### ISSUE TITLE
The source code

### ISSUE THREAD

**Issue by severous** [mangushev/mtad-gat#1]
@mangushev  Thanks for your work.Is this the official implementation of MTAD-GAT about your repository.The model of my implementation gets good performence in MSL.but the performence is very pool in SMAP dataset.I would like to konw if you eval the model in SMAP dataset

**Comment by mangushev** [comment]
Hi, I actually used SMD from omnianomaly https://github.com/NetManAIOps/OmniAnomaly
This is a server computer anomaly data. I did not use SMAP or MSL.

**Comment by severous** [comment]
> Hi, I actually used SMD from omnianomaly https://github.com/NetManAIOps/OmniAnomaly
> This is a server computer anomaly data. I did not use SMAP or MSL.

thanks for your reply :)

**Comment by mangushev** [comment]
Closing
