### ISSUE TITLE
Why make the conv1d_output equal to input_t in model.py?

### ISSUE THREAD

**Issue by UrsulaPan** [mangushev/mtad-gat#6]

**Comment by mangushev** [comment]
Please use it as commented or uncommented. The issue is if this conv helps or not. I recollect I was struggling with NaNs and I was looking into causes. This conv step supposedly should help with performance. It is done the same way in mtad-tf.

**Comment by UrsulaPan** [comment]
> Please use it as commented or uncommented. The issue is if this conv helps or not. I recollect I was struggling with NaNs and I was looking into causes. This conv step supposedly should help with performance. It is done the same way in mtad-tf.

thank you for your reply.I have another problem，what's your version of tensorflow ,when i use 1.15.0,but get the error AttributeError: module 'tensorflow._api.v1.compat.v1' has no attribute 'estimator'

**Comment by mangushev** [comment]
Hi , I looked up with google to see why such an error can be. It seems that package is required. Please put a proper version after ==

pip install tensorflow-estimator==

I’m using 2.x now. I can check or test it.

**Comment by UrsulaPan** [comment]
I'm using 2.x too,I wanted to check your example result by 1.x，because i get the pool recall and precision with the data  machine-1-1.txt，But i can't find the problem,can I get your other contact ？

**Comment by mangushev** [comment]
Rynad.Mangushev at gmail dot com

**Comment by mangushev** [comment]
Closing , considering answered
